baseURL = 'https://amico.aimoverse.xyz/'
languageCode = 'en-us'
title = 'Amico Docs'
theme = "hugo-theme-monochrome"

[params]
navbar_title = 'Amico Docs'
footer = "Copyright © 2025 the Amico Community"
enable_math = true
enable_site_search = true
author = "Takasaki"

[outputs]
home = ["HTML", "RSS", "JSON"]
